"""add share_token to trips

Revision ID: 2299e3a984cd
Revises: 5be23749daea
Create Date: 2026-09-21 09:16:26.117918
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2299e3a984cd'
down_revision: str | None = '5be23749daea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('share_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_trips_share_token'), 'trips', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_share_token'), table_name='trips')
    op.drop_column('trips', 'share_token')
    # ### end Alembic commands ###