"""add plan_tasks and trip owner

Revision ID: 628efba1a3e5
Revises: 9e17aafdca74
Create Date: 2026-09-19 15:04:47.176718
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '628efba1a3e5'
down_revision: str | None = '9e17aafdca74'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('trip_id', sa.String(length=36), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_tasks_owner'), 'plan_tasks', ['owner'], unique=False)
    op.create_index(op.f('ix_plan_tasks_status'), 'plan_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_plan_tasks_trip_id'), 'plan_tasks', ['trip_id'], unique=False)
    op.alter_column('trip_plans', 'provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('trips', sa.Column('owner', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_trips_owner'), 'trips', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_owner'), table_name='trips')
    op.drop_column('trips', 'owner')
    op.alter_column('trip_plans', 'provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_plan_tasks_trip_id'), table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_status'), table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_owner'), table_name='plan_tasks')
    op.drop_table('plan_tasks')
    # ### end Alembic commands ###