"""add trip_comments and stop_votes for share collab

Revision ID: e5302ddbcdd2
Revises: 2299e3a984cd
Create Date: 2026-09-23 03:47:27.911874
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e5302ddbcdd2'
down_revision: str | None = '2299e3a984cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('author_name', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_comments_trip_id'), 'trip_comments', ['trip_id'], unique=False)
    op.create_table('stop_votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stop_id', sa.String(length=36), nullable=False),
    sa.Column('voter_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stop_id', 'voter_key', name='uq_stop_votes_stop_voter')
    )
    op.create_index(op.f('ix_stop_votes_stop_id'), 'stop_votes', ['stop_id'], unique=False)
    op.create_index(op.f('ix_stop_votes_voter_key'), 'stop_votes', ['voter_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stop_votes_voter_key'), table_name='stop_votes')
    op.drop_index(op.f('ix_stop_votes_stop_id'), table_name='stop_votes')
    op.drop_table('stop_votes')
    op.drop_index(op.f('ix_trip_comments_trip_id'), table_name='trip_comments')
    op.drop_table('trip_comments')
    # ### end Alembic commands ###