"""add edit_token to trips and checked to stops

Revision ID: e8c5a9ad4e68
Revises: d71385961648
Create Date: 2026-09-24 01:05:21.697762
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e8c5a9ad4e68'
down_revision: str | None = 'd71385961648'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stops', sa.Column('checked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('trips', sa.Column('edit_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_trips_edit_token'), 'trips', ['edit_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_edit_token'), table_name='trips')
    op.drop_column('trips', 'edit_token')
    op.drop_column('stops', 'checked')
    # ### end Alembic commands ###